name: publish
on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: release
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
          docker build . --tag ghcr.io/rsum1/pktMiner:${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/rsum1/pktMiner:${GITHUB_REF#refs/tags/} ghcr.io/rsum1/pktMiner:latest
          docker push ghcr.io/rsum1/pktMiner:${GITHUB_REF#refs/tags/}
          docker push ghcr.io/rsum1/pktMiner:latest
